services:
  db:
    container_name: oracle-db-locaweb
    image: 'gvenzl/oracle-free:latest'
    ports:
      - "1521:1521"
    environment:
      - 'ORACLE_PASSWORD=secret'

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
      - DATABASE_USER=rm551136
      - DATABASE_PWD=270400