CREATE SEQUENCE SQ_EMAILS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TB_EMAILS (
    ID_EMAIL INTEGER DEFAULT SQ_EMAILS.NEXTVAL NOT NULL,
    DS_DESTINATION VARCHAR2(100) NOT NULL,
    NM_TITLE VARCHAR2(100) NOT NULL,
    DS_SUBJECT VARCHAR2(300) NOT NULL,
    DT_DATE DATE,
    ST_STATUS VARCHAR2(20) DEFAULT 'inbox',
    ID_USER INTEGER NOT NULL,
    CONSTRAINT FK_USER_EMAIL FOREIGN KEY (ID_USER) REFERENCES TB_USERS(ID_USER),
    PRIMARY KEY (ID_EMAIL)
)