CREATE SEQUENCE SQ_SPAM_USERS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TB_SPAM_USERS (
    ID_SPAM INTEGER DEFAULT SQ_SPAM_USERS.NEXTVAL NOT NULL,
    ID_USER INTEGER NOT NULL,
    ID_SPAM_USER INTEGER NOT NULL,
    CONSTRAINT FK_USER_SPAM FOREIGN KEY (ID_USER) REFERENCES TB_USERS(ID_USER),
    CONSTRAINT FK_SPAM_USER FOREIGN KEY (ID_SPAM_USER) REFERENCES TB_USERS(ID_USER),
    PRIMARY KEY (ID_SPAM)
);